name: Build ubuntu-workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'ubuntu-workflow/**'
      - '.github/workflows/ubuntu-workflow.yml'
    tags:
      - 'ubuntu-workflow-v*'
  pull_request:
    paths:
      - 'ubuntu-workflow/**'
      - '.github/workflows/ubuntu-workflow.yml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: ubuntu-workflow
      context: ./ubuntu-workflow
      push: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write
